name: chatcart
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - discord.py==2.3.1
    - elasticsearch==8.8.1
    - openai==0.27.8
    - python-dotenv==1.0.0
    - cachetools==5.3.0
    - aiohttp==3.8.4
    - pytest==7.3.1
